// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	model "github.com/fignocius/logic-api/api/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// LogicRepository is an autogenerated mock type for the LogicRepository type
type LogicRepository struct {
	mock.Mock
}

// Apply provides a mock function with given fields: _a0, _a1
func (_m *LogicRepository) Apply(_a0 string, _a1 []interface{}) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []interface{}) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, []interface{}) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, []interface{}) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: _a0
func (_m *LogicRepository) Create(_a0 model.Logic) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Logic) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *LogicRepository) Delete(_a0 uuid.UUID) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: _a0
func (_m *LogicRepository) Get(_a0 uuid.UUID) (model.Logic, error) {
	ret := _m.Called(_a0)

	var r0 model.Logic
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (model.Logic, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) model.Logic); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.Logic)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *LogicRepository) List() ([]model.Logic, error) {
	ret := _m.Called()

	var r0 []model.Logic
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]model.Logic, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []model.Logic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Logic)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *LogicRepository) Update(_a0 model.Logic) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Logic) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLogicRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogicRepository creates a new instance of LogicRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogicRepository(t mockConstructorTestingTNewLogicRepository) *LogicRepository {
	mock := &LogicRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
